Run pipeline

diff --git a/.github/workflows/targets.yaml b/.github/workflows/targets.yaml
--- a/.github/workflows/targets.yaml
+++ b/.github/workflows/targets.yaml
@@ -103,28 +103,36 @@ jobs:
         continue-on-error: true # if the pipeline fails, the workspace is saved for inspection.
 
       - name: Identify files that the targets pipeline produced
-        run: git ls-files -mo -x renv -x inst > .targets-files
+        id: check-new-files
+        run: |
+          git ls-files -mo -x renv -x inst -x src > .targets-files
+          ([ -s .targets-files ] && echo "New files produced" && cat .targets-files && echo "::set-output name=newfiles::true") || (echo "Nothing to do" && echo "::set-output name=newfiles::false")
 
       - name: Update the current repository without the objects
+        if: steps.check-new-files.outputs.newfiles == 'true'
         run: |
           git config --local user.name "GitHub Actions"
           git config --local user.email "actions@github.com"
           git add --all -- ':!renv'
           git commit -am "Update current branch"
           git push
+        continue-on-error: true # if the pipeline fails, the workspace is saved for inspection.
 
       - name: Create the runs branch if it does not already exist
-        if: steps.runs-exist.outcome != 'success'
+        if: steps.check-new-files.outputs.newfiles == 'true' && steps.runs-exist.outcome != 'success'
         run: git checkout --orphan targets-runs
+        continue-on-error: true # if the pipeline fails, the workspace is saved for inspection.
 
       - name: Put the worktree in the runs branch if the latter already exists
-        if: steps.runs-exist.outcome == 'success'
+        if: steps.check-new-files.outputs.newfiles == 'true' && steps.runs-exist.outcome == 'success'
         run: |
           rm -r .git
           mv .targets-runs/.git .
           rm -r .targets-runs
+        continue-on-error: true # if the pipeline fails, the workspace is saved for inspection.
 
       - name: Upload latest run to the runs branch
+        if: steps.check-new-files.outputs.newfiles == 'true'
         run: |
           git config --local user.name "GitHub Actions"
           git config --local user.email "actions@github.com"
@@ -133,4 +141,5 @@ jobs:
           git add -f _targets
           git commit -am "Run pipeline"
           git push origin targets-runs
+        continue-on-error: true # if the pipeline fails, the workspace is saved for inspection.
 
